# Extra stuff from Chapter 1 notebooks

In [8]:
import pandas as pd
import numpy as np

### Random sampling alternatives

In [2]:
import random
random.seed(22)

In [3]:
# select sample of 20 from 100 individuals
pop1 = range(1,101)
print(sorted(random.sample(pop1, 20)))

[4, 7, 11, 16, 18, 23, 24, 30, 32, 35, 41, 45, 58, 71, 77, 79, 84, 88, 90, 95]

In [4]:
# 5 strata of 20 individuals
strata = [range(1,21) for s in range(5)]
for statum in strata:
    print(sorted(random.sample(statum, 4)))

[1, 2, 9, 14]
[6, 7, 10, 14]
[2, 4, 17, 19]
[6, 9, 11, 20]
[5, 10, 13, 17]

In [5]:
# choose 2 clusters out of 10
clusters = range(1,11)
print(sorted(random.sample(clusters, 2)))

[5, 10]

In [9]:
students = pd.read_csv("../datasets/students.csv")
cov_matrix = students[["effort", "score"]].cov()

stde = students["effort"].std()
stds = students["score"].std()
denom = np.array([[stde*stde, stde*stds],
                  [stds*stde, stds*stds]])

corr_matrix = cov_matrix / denom
corr_matrix  # == students[["effort", "score"]].corr()

          effort     score
effort  1.000000  0.879438
score   0.879438  1.000000

In [10]:
students[["effort", "score"]].corr()

          effort     score
effort  1.000000  0.879438
score   0.879438  1.000000